require("dotenv").config();
const simpleGit = require("simple-git");
const { Octokit } = require("@octokit/rest");
const fs = require("fs");
const path = require("path");

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

async function createFixBranch(plan, issueNumber, review) {
  const git = simpleGit(process.cwd());
  const branchName = `auto-fix/issue-${issueNumber}`;

  try {
    // Fetch latest and switch to main
    await git.fetch("origin");
    await git.checkout("main");
    await git.pull("origin", "main");

    // Create new branch
    await git.checkoutLocalBranch(branchName);
    console.log(`✅ Created branch: ${branchName}`);

    // Write each fixed file to disk
    for (const file of plan.filesToChange) {
      const fullPath = path.join(process.cwd(), file.path);
      const dir = path.dirname(fullPath);

      // Create directories if they don't exist
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

      fs.writeFileSync(fullPath, file.fixedContent, "utf-8");
      console.log(`📝 Fixed: ${file.path}`);
    }

    // Stage, commit and push
    await git.add(".");
    await git.commit(`fix: auto-resolve issue #${issueNumber} - ${plan.summary}`);
    await git.push("origin", branchName);
    console.log(`🚀 Pushed branch: ${branchName}`);

    return branchName;
  } catch (err) {
    console.error("❌ Git error:", err.message);
    throw err;
  }
}

async function openPullRequest(branchName, plan, issueNumber, review) {
  const filesChanged = plan.filesToChange
    .map((f) => `- \`${f.path}\`: ${f.explanation}`)
    .join("\n");

  const prBody = `
## 🤖 Auto-generated Fix for Issue #${issueNumber}

### Root Cause
${plan.rootCause}

### Changes Made
${filesChanged}

### Self-Review Result
- **Approved:** ${review.approved ? "✅ Yes" : "❌ No"}
- **Confidence:** ${review.confidence}
- **Review Notes:** ${review.reviewComment}

---
*This PR was automatically generated by the GitHub Issue Resolver Agent.*
  `.trim();

  const { data: pr } = await octokit.pulls.create({
    owner: process.env.REPO_OWNER,
    repo: process.env.REPO_NAME,
    title: `🤖 Auto-fix: ${plan.summary}`,
    head: branchName,
    base: "main",
    body: prBody,
  });

  console.log(`✅ PR created: ${pr.html_url}`);
  return pr;
}

module.exports = { createFixBranch, openPullRequest };
